from database import GovernmentScheme

MOCK_SCHEME_LIST = [
    # ── INSURANCE & BASIC INCOME (Central) ──────────────────────────────
    GovernmentScheme(
        id="SCHEME_001",
        name="PM Kisan Samman Nidhi",
        short_description="Direct income support of ₹6,000 per year for farmer families.",
        full_description="An income support of 6000/- per year in three equal installments will be provided to all land holding farmer families.",
        benefits=["₹6,000 per year in 3 installments", "Direct bank transfer"],
        eligibility_rules=["Must own cultivable land"],
        required_documents=["Aadhaar Card", "Bank Passbook", "Land Ownership Proof"],
        application_process=["Visit local CSC or pmkisan.gov.in"],
        official_link="https://pmkisan.gov.in/",
        ministry="Ministry of Agriculture",
        scheme_type="Income Support",
        target_beneficiary="All Landholding Farmers",
        supported_states=["All India"],
        ai_summary="The government gives you ₹6,000 every year straight into your bank account.",
        ai_farmer_explanation="This scheme helps you with ₹6,000 a year to buy seeds or fertilizer. You get ₹2,000 every 4 months.",
        ai_short_benefit_line="Get ₹6,000 cash per year",
        thumbnail_icon="cash",
        languages_available=["en"],
        translations={}
    ),
    GovernmentScheme(
        id="SCHEME_002",
        name="Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        short_description="Crop insurance scheme against non-preventable natural risks.",
        full_description="Provides comprehensive insurance cover against failure of the crop thus helping in stabilizing the income of the farmers.",
        benefits=["Financial support for crop loss", "Low premium rates"],
        eligibility_rules=["Must be a farmer growing notified crops in notified areas"],
        required_documents=["Land documents", "Aadhaar Card", "Bank details", "Sowing certificate"],
        application_process=["Apply through bank branch or PMFBY portal"],
        official_link="https://pmfby.gov.in/",
        ministry="Ministry of Agriculture",
        scheme_type="Insurance",
        target_beneficiary="All Farmers",
        supported_states=["All India"],
        ai_summary="Get paid if your crop gets destroyed by bad weather.",
        ai_farmer_explanation="If a flood or drought kills your crop, the government gives you money so you don't go broke.",
        ai_short_benefit_line="Insurance for crop damage",
        thumbnail_icon="shield",
        languages_available=["en"],
        translations={}
    ),

    # ── INFRASTRUCTURE & SOLAR ──────────────────────────────────────────
    GovernmentScheme(
        id="SCHEME_003",
        name="PM KUSUM (Solar Pumps)",
        short_description="Provides subsidies for setting up standalone solar pumps.",
        full_description="Pradhan Mantri Kisan Urja Suraksha evam Utthaan Mahabhiyan (PM-KUSUM) aims to add solar and other renewable capacity.",
        benefits=["60% subsidy on Solar Pumps", "Sell excess power to grid"],
        eligibility_rules=["Farmers holding agricultural land"],
        required_documents=["Aadhaar", "Land ownership", "Bank passbook"],
        application_process=["Apply via state nodal agencies"],
        official_link="https://mnre.gov.in/",
        ministry="Ministry of New and Renewable Energy",
        scheme_type="Infrastructure",
        target_beneficiary="All Farmers",
        supported_states=["All India"],
        ai_summary="The government pays 60% of the cost to install a solar water pump.",
        ai_farmer_explanation="Stop paying for diesel. The government will help you buy a solar-powered water pump, and you can even sell extra electricity back to them.",
        ai_short_benefit_line="60% off Solar Pumps",
        thumbnail_icon="sun",
        languages_available=["en"],
        translations={}
    ),
    GovernmentScheme(
        id="SCHEME_004",
        name="Pradhan Mantri Krishi Sinchai Yojana (PMKSY)",
        short_description="Subsidies for irrigation equipment like drip and sprinklers.",
        full_description="Aims to enhance physical access of water on farm and expand cultivable area.",
        benefits=["Up to 55% subsidy on micro-irrigation tools"],
        eligibility_rules=["Must own agricultural land"],
        required_documents=["Land ownership proof", "Aadhaar", "Bank passbook"],
        application_process=["Apply through state agriculture department"],
        official_link="https://pmksy.gov.in/",
        ministry="Ministry of Agriculture",
        scheme_type="Infrastructure",
        target_beneficiary="All Farmers",
        supported_states=["All India"],
        ai_summary="Discount on buying water drip and sprinkler systems.",
        ai_farmer_explanation="The government will pay for more than half the cost if you want to install pipes or sprinklers on your land.",
        ai_short_benefit_line="55% off irrigation tools",
        thumbnail_icon="droplet",
        languages_available=["en"],
        translations={}
    ),
    GovernmentScheme(
        id="SCHEME_005",
        name="Agriculture Infrastructure Fund (AIF)",
        short_description="Debt financing facility for post-harvest management infrastructure.",
        full_description="Providing medium - long term debt financing facility for investment in viable projects for post-harvest management.",
        benefits=["3% interest subvention", "Credit guarantee"],
        eligibility_rules=["FPOs, SHGs, Farmers, Cooperatives"],
        required_documents=["Detailed project report (DPR)", "KYC documents"],
        application_process=["Register and apply on AIF portal"],
        official_link="https://agriinfra.dac.gov.in/",
        ministry="Ministry of Agriculture",
        scheme_type="Infrastructure",
        target_beneficiary="Farmer Groups",
        supported_states=["All India"],
        ai_summary="Cheap loans to build warehouses or cold storage.",
        ai_farmer_explanation="If you or your farmer group wants to build a cold room to store vegetables, you can get a loan with very low interest.",
        ai_short_benefit_line="Low interest loans",
        thumbnail_icon="warehouse",
        languages_available=["en"],
        translations={}
    ),

    # ── MECHANIZATION & SUBSIDIES ───────────────────────────────────────
    GovernmentScheme(
        id="SCHEME_006",
        name="Sub-Mission on Agricultural Mechanization (SMAM)",
        short_description="Subsidies for buying tractors and farming machinery.",
        full_description="Aims to increase the reach of farm mechanization to small and marginal farmers.",
        benefits=["Up to 50% subsidy on buying tractors and equipment"],
        eligibility_rules=["Must own land", "Small/Marginal/SC/ST/Women farmers get higher subsidies"],
        required_documents=["Aadhaar", "Land records", "Quotation of machinery"],
        application_process=["Apply on State Agriculture Machinery Portal"],
        official_link="https://farmech.dac.gov.in/",
        ministry="Ministry of Agriculture",
        scheme_type="Mechanization",
        target_beneficiary="Small and Marginal Farmers",
        supported_states=["All India"],
        ai_summary="Get a massive discount on a tractor or tiller.",
        ai_farmer_explanation="If you need a tractor or a plow, the government will pay up to half the cost if your farm is small.",
        ai_short_benefit_line="50% off farm machines",
        thumbnail_icon="tractor",
        languages_available=["en"],
        translations={}
    ),
    GovernmentScheme(
        id="SCHEME_007",
        name="Paramparagat Krishi Vikas Yojana (PKVY)",
        short_description="Promotes organic farming through cluster approach.",
        full_description="Financial assistance is given to farmers for organic inputs, certification, and marketing.",
        benefits=["₹50,000 per hectare over 3 years"],
        eligibility_rules=["Farmers willing to switch to organic farming"],
        required_documents=["Aadhaar", "Land records", "Cluster membership"],
        application_process=["Contact local agriculture officer"],
        official_link="https://pgsindia-ncof.gov.in/",
        ministry="Ministry of Agriculture",
        scheme_type="Subsidies",
        target_beneficiary="Organic Farmers",
        supported_states=["All India"],
        ai_summary="Get paid to switch to chemical-free organic farming.",
        ai_farmer_explanation="If you group up with your neighbors and agree to stop using chemicals, the government pays you ₹50,000 over 3 years.",
        ai_short_benefit_line="₹50k for Organic Farming",
        thumbnail_icon="leaf",
        languages_available=["en"],
        translations={}
    ),
    GovernmentScheme(
        id="SCHEME_008",
        name="Soil Health Card Scheme",
        short_description="Provides soil health cards to farmers with crop-wise recommendations.",
        full_description="Government issues Soil Health Cards containing crop-wise recommendations of nutrients and fertilizers.",
        benefits=["Free soil testing", "Custom fertilizer plan"],
        eligibility_rules=["All farmers are eligible"],
        required_documents=["None directly"],
        application_process=["Contact local agriculture office for farm test"],
        official_link="https://soilhealth.dac.gov.in/",
        ministry="Ministry of Agriculture",
        scheme_type="Subsidies",
        target_beneficiary="All Farmers",
        supported_states=["All India"],
        ai_summary="Free testing of your land's soil.",
        ai_farmer_explanation="Scientists will check your soil for free and tell you exactly which fertilizer you actually need.",
        ai_short_benefit_line="Free soil report",
        thumbnail_icon="flask",
        languages_available=["en"],
        translations={}
    ),

    # ── ANIMAL HUSBANDRY & FISHERIES ────────────────────────────────────
    GovernmentScheme(
        id="SCHEME_009",
        name="National Livestock Mission (NLM)",
        short_description="Subsidies for poultry, sheep, goat, and pig farming.",
        full_description="Enhances livestock productivity and provides entrepreneurship support.",
        benefits=["50% capital subsidy (up to ₹50 Lakh)"],
        eligibility_rules=["Individuals, FPOs, and SHGs"],
        required_documents=["Aadhaar", "Bank Details", "Project plan"],
        application_process=["Apply through NLM portal"],
        official_link="https://nlm.udyamimitra.in/",
        ministry="Ministry of Animal Husbandry",
        scheme_type="Animal Husbandry",
        target_beneficiary="Livestock Farmers",
        supported_states=["All India"],
        ai_summary="Massive grants to start a goat, sheep, or poultry farm.",
        ai_farmer_explanation="If you want to start raising goats or chickens commercially, the government will fund half your startup costs.",
        ai_short_benefit_line="50% off livestock setup",
        thumbnail_icon="cow",
        languages_available=["en"],
        translations={}
    ),
    GovernmentScheme(
        id="SCHEME_010",
        name="Pradhan Mantri Matsya Sampada Yojana (PMMSY)",
        short_description="Scheme to bring about Blue Revolution through sustainable development of fisheries.",
        full_description="Provides financial assistance for boats, nets, fish ponds, and cold chains.",
        benefits=["Up to 60% subsidy for livelihood projects"],
        eligibility_rules=["Fish Farmers and Fish Vendors"],
        required_documents=["Aadhaar", "Bank Details", "Project plan"],
        application_process=["Apply through Department of Fisheries"],
        official_link="https://pmmsy.dof.gov.in/",
        ministry="Department of Fisheries",
        scheme_type="Fisheries",
        target_beneficiary="Fish Farmers",
        supported_states=["All India"],
        ai_summary="Grants to start a fish farm or buy fishing gear.",
        ai_farmer_explanation="If you want to dig a pond and sell fish, the government will pay for more than half of your setup costs.",
        ai_short_benefit_line="60% off Fish Farming",
        thumbnail_icon="fish",
        languages_available=["en"],
        translations={}
    ),
    GovernmentScheme(
        id="SCHEME_011",
        name="Rashtriya Gokul Mission",
        short_description="Development and conservation of indigenous bovine breeds.",
        full_description="Provides funds for establishing artificial insemination centers and breed conservation.",
        benefits=["Grants for dairy infrastructure"],
        eligibility_rules=["Dairy Cooperatives, FPOs, Individual farmers"],
        required_documents=["Land and shed details", "State nodal officer approval"],
        application_process=["Contact State Livestock Board"],
        official_link="https://dahd.nic.in/",
        ministry="Ministry of Animal Husbandry",
        scheme_type="Animal Husbandry",
        target_beneficiary="Dairy Farmers",
        supported_states=["All India"],
        ai_summary="Support for breeding high-quality Indian cows.",
        ai_farmer_explanation="If you run a dairy farm, you can get financial help to breed better cows that produce more milk.",
        ai_short_benefit_line="Dairy breeding support",
        thumbnail_icon="view-list",
        languages_available=["en"],
        translations={}
    ),

    # ── HORTICULTURE (Fruits, Veg, Cash crops) ─────────────────────────
    GovernmentScheme(
        id="SCHEME_012",
        name="Mission for Integrated Development of Horticulture (MIDH)",
        short_description="Promotes holistic growth of the horticulture sector.",
        full_description="Subsidies for planting orchards, building greenhouses, and polyhouses.",
        benefits=["Up to 50% subsidy on greenhouses and cold storage"],
        eligibility_rules=["Farmers growing fruits, vegetables, flowers, or spices"],
        required_documents=["Land documents", "Project details", "Quotation"],
        application_process=["Through State Horticulture Department"],
        official_link="https://midh.gov.in/",
        ministry="Ministry of Agriculture",
        scheme_type="Horticulture",
        target_beneficiary="Orchard & Veg Farmers",
        supported_states=["All India"],
        ai_summary="Get half the money back for building a greenhouse.",
        ai_farmer_explanation="If you want to grow expensive vegetables in a polyhouse or plant fruit trees, the government will pay 50% of the cost.",
        ai_short_benefit_line="50% off Greenhouses",
        thumbnail_icon="sprout",
        languages_available=["en"],
        translations={}
    ),

    # ── STATE SPECIFIC SCHEMES ──────────────────────────────────────────
    # Maharashtra
    GovernmentScheme(
        id="SCHEME_013",
        name="Maharashtra Mahatma Jotirao Phule Shetkari Karjmukti Yojana",
        short_description="Farm loan waiver scheme for Maharashtra farmers.",
        full_description="Provides waiver of crop loans outstanding up to Rs 2 lakh.",
        benefits=["Loan waiver up to ₹200,000"],
        eligibility_rules=["Must be a resident of Maharashtra", "Have outstanding crop loans"],
        required_documents=["Aadhaar synced to bank account", "Loan details"],
        application_process=["Aadhaar authentication via CSC centers"],
        official_link="https://krishi.maharashtra.gov.in/",
        ministry="Govt of Maharashtra",
        scheme_type="Debt Relief",
        target_beneficiary="Debt-ridden Farmers",
        supported_states=["Maharashtra"],
        ai_summary="Your farm loan up to 2 lakh rupees will be forgiven.",
        ai_farmer_explanation="If you took a loan for crops and are struggling to pay it, the Maharashtra government will clear up to 2 lakhs of your debt.",
        ai_short_benefit_line="Debt wipe up to ₹2 Lakh",
        thumbnail_icon="minus-circle",
        languages_available=["en"],
        translations={}
    ),
    GovernmentScheme(
        id="SCHEME_014",
        name="Bhausaheb Fundkar Orchard Planting Scheme",
        short_description="100% subsidy for planting fruit orchards in Maharashtra.",
        full_description="Provides plants and maintenance cost for 3 years to grow orchards.",
        benefits=["Free saplings and maintenance money for 3 years"],
        eligibility_rules=["Must be a resident of Maharashtra", "Land size minimums apply"],
        required_documents=["7/12 extract", "8-A abstract"],
        application_process=["MahaDBT portal"],
        official_link="https://mahadbt.maharashtra.gov.in/",
        ministry="Govt of Maharashtra",
        scheme_type="Horticulture",
        target_beneficiary="Small Farmers",
        supported_states=["Maharashtra"],
        ai_summary="Free fruit trees and money to take care of them.",
        ai_farmer_explanation="If you want to plant a mango or pomegranate orchard, the government gives you free trees and pays you for 3 years to water them.",
        ai_short_benefit_line="Free Orchard Planting",
        thumbnail_icon="tree",
        languages_available=["en"],
        translations={}
    ),

    # Madhya Pradesh
    GovernmentScheme(
        id="SCHEME_015",
        name="Bhavantar Bhugtan Yojana (MP)",
        short_description="Protects farmers from distress sales during price drops.",
        full_description="Government pays the difference between the official Minimum Support Price (MSP) and the lower market rate.",
        benefits=["Cash transfer equal to the price difference"],
        eligibility_rules=["Farmers of Madhya Pradesh growing notified crops"],
        required_documents=["B-1 land records", "Aadhaar"],
        application_process=["Register at MP e-Uparjan portal"],
        official_link="http://mpeuparjan.nic.in/",
        ministry="Govt of Madhya Pradesh",
        scheme_type="Income Support",
        target_beneficiary="MP Farmers",
        supported_states=["Madhya Pradesh"],
        ai_summary="The government pays you if the market price drops below MSP.",
        ai_farmer_explanation="If the market price of your crop suddenly drops, the government will pay you cash to make up the difference to the MSP.",
        ai_short_benefit_line="Price Crash Protection",
        thumbnail_icon="trending-down",
        languages_available=["en"],
        translations={}
    ),
    GovernmentScheme(
        id="SCHEME_016",
        name="Mukhyamantri Kisan Kalyan Yojana (MP)",
        short_description="Additional financial assistance to PM-Kisan beneficiaries in MP.",
        full_description="Transfers an additional ₹6,000 per year over and above the ₹6,000 from Central PM-KISAN.",
        benefits=["Extra ₹6,000 per year (Total ₹12,000 with PM-Kisan)"],
        eligibility_rules=["Must be a resident of MP and enrolled in PM-KISAN"],
        required_documents=["Aadhaar", "Bank Account registered in PM-Kisan"],
        application_process=["Auto-credited to PM-Kisan beneficiaries"],
        official_link="https://saara.mp.gov.in/",
        ministry="Govt of Madhya Pradesh",
        scheme_type="Income Support",
        target_beneficiary="Landholding Farmers",
        supported_states=["Madhya Pradesh"],
        ai_summary="Double your PM-Kisan money from the State Government.",
        ai_farmer_explanation="Because you live in MP, the state gives you an extra ₹6,000 on top of the central government's ₹6,000, bringing your total to ₹12,000 a year.",
        ai_short_benefit_line="Extra ₹6,000 cash yearly",
        thumbnail_icon="cash",
        languages_available=["en"],
        translations={}
    ),

    # Uttar Pradesh
    GovernmentScheme(
        id="SCHEME_017",
        name="UP Krishi Yantra Subsidy Yojana",
        short_description="Grants for purchasing modern agricultural equipment.",
        full_description="Offers up to 50% subsidy on buying costly farming equipment like combined harvesters, laser levelers.",
        benefits=["50% subsidy on heavy farm machinery"],
        eligibility_rules=["UP Resident farmer", "Registered on Darshan portal"],
        required_documents=["Aadhaar", "Token booking receipt"],
        application_process=["Book token online via UP Agriculture portal"],
        official_link="http://upagriculture.com/",
        ministry="Govt of Uttar Pradesh",
        scheme_type="Mechanization",
        target_beneficiary="Machine Buyers",
        supported_states=["Uttar Pradesh"],
        ai_summary="Half price on expensive farming machines like Harvesters.",
        ai_farmer_explanation="If you live in UP, book a token online to get a massive 50% discount on expensive machines like laser land levelers or harvesters.",
        ai_short_benefit_line="50% off Heavy Machinery",
        thumbnail_icon="truck",
        languages_available=["en"],
        translations={}
    ),

    # Bihar
    GovernmentScheme(
        id="SCHEME_018",
        name="Bihar Krishi Input Subsidy Scheme",
        short_description="Grant for farmers whose crops were destroyed by drought or floods.",
        full_description="Provides cash directly into bank accounts for crop failure due to extreme weather in Bihar.",
        benefits=["₹6,800 to ₹13,500 per hectare based on rain/irrigation status"],
        eligibility_rules=["Bihar resident", "Crop loss due to notified disaster"],
        required_documents=["LPC (Land Possession Certificate)", "Aadhaar"],
        application_process=["Apply through DBT Agriculture Bihar Portal"],
        official_link="https://dbtagriculture.bihar.gov.in/",
        ministry="Govt of Bihar",
        scheme_type="Insurance",
        target_beneficiary="Disaster Affected Farmers",
        supported_states=["Bihar"],
        ai_summary="Emergency cash if a flood or drought ruins your field.",
        ai_farmer_explanation="If the Bihar floods destroy your crop, the government will send between ₹6,800 and ₹13,500 per hectare directly to your bank account to help you survive.",
        ai_short_benefit_line="Emergency disaster cash",
        thumbnail_icon="alert-triangle",
        languages_available=["en"],
        translations={}
    ),

    # Punjab / Haryana
    GovernmentScheme(
        id="SCHEME_019",
        name="Crop Residue Management (CRM) Scheme",
        short_description="Subsidies to stop stubble burning (Parali).",
        full_description="Provides 50% to 80% subsidy on machines like Happy Seeder and Super SMS to manage paddy straw without burning.",
        benefits=["Up to 80% subsidy for Custom Hiring Centers (CHCs)", "50% for individuals"],
        eligibility_rules=["Farmers in Punjab, Haryana, UP, and Delhi NCR"],
        required_documents=["Aadhaar", "Machine Quotation"],
        application_process=["Apply via State Agriculture Dept"],
        official_link="https://agricoop.nic.in/",
        ministry="Ministry of Agriculture",
        scheme_type="Mechanization",
        target_beneficiary="Paddy Farmers",
        supported_states=["Punjab", "Haryana", "Uttar Pradesh", "Delhi"],
        ai_summary="Massive discounts on machines that handle stubble so you don't burn it.",
        ai_farmer_explanation="To stop air pollution, the government pays 80% of the cost if a village group buys a Happy Seeder machine to cut Parali instead of burning it.",
        ai_short_benefit_line="80% off Parali Machines",
        thumbnail_icon="wind",
        languages_available=["en"],
        translations={}
    ),

    # Gujarat
    GovernmentScheme(
        id="SCHEME_020",
        name="Mukhyamantri Kisan Sahay Yojana (Gujarat)",
        short_description="Zero-premium crop insurance for Gujarat farmers.",
        full_description="Unlike PMFBY, farmers don't pay any premium. State covers the risk of drought, excess rain, or unseasonal rain.",
        benefits=["₹20,000 to ₹25,000 per hectare compensation"],
        eligibility_rules=["Gujarat resident farmer"],
        required_documents=["8-A and 7/12 land extracts", "Talati damage report"],
        application_process=["Through i-Khedut portal"],
        official_link="https://ikhedut.gujarat.gov.in/",
        ministry="Govt of Gujarat",
        scheme_type="Insurance",
        target_beneficiary="Gujarat Farmers",
        supported_states=["Gujarat"],
        ai_summary="Free crop insurance with no premium payments.",
        ai_farmer_explanation="You don't have to pay a single Rupee for insurance. If bad weather hits Gujarat, the State will automatically pay you up to ₹25,000 per hectare.",
        ai_short_benefit_line="Zero-Premium Insurance",
        thumbnail_icon="shield",
        languages_available=["en"],
        translations={}
    ),

    # Andhra Pradesh / Telangana
    GovernmentScheme(
        id="SCHEME_021",
        name="Rythu Bandhu / Rythu Bharosa",
        short_description="Investment support scheme providing cash per acre before the sowing season.",
        full_description="Gives farmers cash before Kharif and Rabi seasons to take care of initial investment needs like seeds and fertilizers.",
        benefits=["₹5,000+ per acre per season direct cash transfer"],
        eligibility_rules=["Landowning farmers in AP/Telangana"],
        required_documents=["Pattadar passbook", "Aadhaar"],
        application_process=["Automatically credited to eligible landholders"],
        official_link="https://rythubandhu.telangana.gov.in/",
        ministry="State Governments (AP/TS)",
        scheme_type="Income Support",
        target_beneficiary="All Landholders",
        supported_states=["Andhra Pradesh", "Telangana"],
        ai_summary="The State gives you flat cash per acre before every season starts.",
        ai_farmer_explanation="Right before it's time to plant, the state government sends you cash into your bank account for every acre you own, so you can afford to buy seeds.",
        ai_short_benefit_line="Pre-season cash per acre",
        thumbnail_icon="banknote",
        languages_available=["en"],
        translations={}
    ),

    # ── ADDITIONAL GENERAL SCHEMES ──────────────────────────────────────
    GovernmentScheme(
        id="SCHEME_022",
        name="National Food Security Mission (NFSM)",
        short_description="Subsidies to increase production of rice, wheat, pulses.",
        full_description="Provides high yielding variety seeds and demonstrations to boost yield.",
        benefits=["Subsidized seeds and training"],
        eligibility_rules=["Farmers growing covered crops"],
        required_documents=["None"],
        application_process=["Through local Krishi Vigyan Kendra (KVK)"],
        official_link="https://nfsm.gov.in/",
        ministry="Ministry of Agriculture",
        scheme_type="Subsidies",
        target_beneficiary="Cereal Farmers",
        supported_states=["All India"],
        ai_summary="Get high quality subsidized seeds for wheat, rice, or pulses.",
        ai_farmer_explanation="The government provides you with better quality seeds at low prices to guarantee your harvest is much bigger.",
        ai_short_benefit_line="Cheap high-yield seeds",
        thumbnail_icon="sprout",
        languages_available=["en"],
        translations={}
    ),
    GovernmentScheme(
        id="SCHEME_023",
        name="National Mission on Edible Oils (NMEO-OP)",
        short_description="Special scheme to promote Oil Palm cultivation.",
        full_description="Provides heavy subsidies for planting material of oil palm to reduce import dependence.",
        benefits=["Subsidized seedlings", "Minimum price assurance"],
        eligibility_rules=["Farmers in identified growing regions (NE & Andaman focused, but open)"],
        required_documents=["Land documents"],
        application_process=["Via State Horticulture Dept"],
        official_link="https://nmeo.dac.gov.in/",
        ministry="Ministry of Agriculture",
        scheme_type="Horticulture",
        target_beneficiary="Oil Palm Growers",
        supported_states=["Andhra Pradesh", "Telangana", "Karnataka"],
        ai_summary="Get heavy grants if you start growing Palm Oil trees.",
        ai_farmer_explanation="If you switch to growing palm oil trees, the government will pay for the saplings and guarantee they buy your harvest.",
        ai_short_benefit_line="Grants for Oil Palm",
        thumbnail_icon="tree",
        languages_available=["en"],
        translations={}
    ),
    GovernmentScheme(
        id="SCHEME_024",
        name="Kisan Credit Card (KCC)",
        short_description="Provides timely and adequate short-term credit to farmers.",
        full_description="Banks issue a credit card explicitly for agricultural expenses with a heavily subsidized interest rate.",
        benefits=["Loan up to ₹3 Lakh at 4% interest (if paid on time)"],
        eligibility_rules=["Any landowning farmer, tenant farmer, or sharecropper"],
        required_documents=["Land holdings", "Identity proof"],
        application_process=["Apply at any commercial or rural bank branch"],
        official_link="https://pmkisan.gov.in/",
        ministry="Ministry of Finance",
        scheme_type="Debt Relief",
        target_beneficiary="All Farmers",
        supported_states=["All India"],
        ai_summary="A credit card for your farm with only 4% interest.",
        ai_farmer_explanation="Unlike a normal high-interest loan, this card lets you borrow money for seeds or fertilizer and only pay 4% interest if you repay after the harvest.",
        ai_short_benefit_line="4% Interest Farm Loans",
        thumbnail_icon="credit-card",
        languages_available=["en"],
        translations={}
    ),
    GovernmentScheme(
        id="SCHEME_025",
        name="National Beekeeping & Honey Mission (NBHM)",
        short_description="Promotion of scientific beekeeping.",
        full_description="Financial assistance for setting up beehives and honey extraction units.",
        benefits=["Subsidies on bee boxes and honey extractors"],
        eligibility_rules=["Farmers and beekeepers"],
        required_documents=["Training certificate from KVK"],
        application_process=["Via National Bee Board portak"],
        official_link="https://nbhm.gov.in/",
        ministry="Ministry of Agriculture",
        scheme_type="Animal Husbandry",
        target_beneficiary="Beekeepers",
        supported_states=["All India"],
        ai_summary="Get funded to start a honey bee business.",
        ai_farmer_explanation="You can make extra income by keeping bees on your farm edges. The government will pay for the bee boxes and the honey extraction machine.",
        ai_short_benefit_line="Subsidies for Bee Boxes",
        thumbnail_icon="hexagon",
        languages_available=["en"],
        translations={}
    )
]
